/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Transaksi.Konsinyasi;
import File.Register;
import Master.DataBarang;
import Master.DataKaryawan;
import Master.DataPenjualan;
import Master.DataRetur;
import Master.DataSupplier;
import Transaksi.Penjualan;
import Transaksi.Retur;
import javax.swing.ImageIcon;

/**
 *
 * @author LREO
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form frameUtama
     */
    public MenuUtama() {
        initComponents();
        this.setExtendedState(MenuUtama.MAXIMIZED_BOTH);
        setIconImage(new ImageIcon(getClass().getResource("/Logo/LogoDNetHouse.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        bLogout = new javax.swing.JMenu();
        bRegister = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        bExit = new javax.swing.JMenuItem();
        mMaster = new javax.swing.JMenu();
        mSupplier = new javax.swing.JMenuItem();
        mBarang = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        bPenjualan = new javax.swing.JMenuItem();
        bRetur = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mKaryawan = new javax.swing.JMenuItem();
        mTransaksi = new javax.swing.JMenu();
        mPenjualan = new javax.swing.JMenuItem();
        mRetur = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mKonsinyasi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Utama | Sistem Informasi Penjualan D-Net House");

        bLogout.setText("Berkas");

        bRegister.setText("Daftar");
        bRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegisterActionPerformed(evt);
            }
        });
        bLogout.add(bRegister);
        bLogout.add(jSeparator1);

        jMenuItem2.setText("Pindah Akun");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        bLogout.add(jMenuItem2);

        bExit.setText("Keluar");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        bLogout.add(bExit);

        jMenuBar1.add(bLogout);

        mMaster.setText("Data");

        mSupplier.setText("Supplier");
        mSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSupplierActionPerformed(evt);
            }
        });
        mMaster.add(mSupplier);

        mBarang.setText("Barang");
        mBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBarangActionPerformed(evt);
            }
        });
        mMaster.add(mBarang);
        mMaster.add(jSeparator3);

        bPenjualan.setText("Penjualan");
        bPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPenjualanActionPerformed(evt);
            }
        });
        mMaster.add(bPenjualan);

        bRetur.setText("Retur");
        bRetur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReturActionPerformed(evt);
            }
        });
        mMaster.add(bRetur);
        mMaster.add(jSeparator5);

        mKaryawan.setText("Karyawan");
        mKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKaryawanActionPerformed(evt);
            }
        });
        mMaster.add(mKaryawan);

        jMenuBar1.add(mMaster);

        mTransaksi.setText("Transaksi");

        mPenjualan.setText("Penjualan");
        mPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPenjualanActionPerformed(evt);
            }
        });
        mTransaksi.add(mPenjualan);

        mRetur.setText("Retur");
        mRetur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mReturActionPerformed(evt);
            }
        });
        mTransaksi.add(mRetur);
        mTransaksi.add(jSeparator7);

        mKonsinyasi.setText("Konsinyasi");
        mKonsinyasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKonsinyasiActionPerformed(evt);
            }
        });
        mTransaksi.add(mKonsinyasi);

        jMenuBar1.add(mTransaksi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegisterActionPerformed
        
        Register show = new Register();
        show.setVisible(true);
        
    }//GEN-LAST:event_bRegisterActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Login Logout = new Login();
        Logout.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    private void mPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPenjualanActionPerformed
        Penjualan show = new Penjualan();
        show.setVisible(true);
    }//GEN-LAST:event_mPenjualanActionPerformed

    private void mReturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mReturActionPerformed
        Retur show = new Retur();
        show.setVisible(true);
    }//GEN-LAST:event_mReturActionPerformed

    private void mKonsinyasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKonsinyasiActionPerformed
        Konsinyasi show = new Konsinyasi();
        show.setVisible(true);
    }//GEN-LAST:event_mKonsinyasiActionPerformed

    private void mSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSupplierActionPerformed
        DataSupplier show = new DataSupplier();
        show.setVisible(true);
    }//GEN-LAST:event_mSupplierActionPerformed

    private void mBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBarangActionPerformed
        DataBarang show = new DataBarang();
        show.setVisible(true);
    }//GEN-LAST:event_mBarangActionPerformed

    private void bPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPenjualanActionPerformed
        DataPenjualan show = new DataPenjualan();
        show.setVisible(true);
    }//GEN-LAST:event_bPenjualanActionPerformed

    private void bReturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReturActionPerformed
        DataRetur show = new DataRetur();
        show.setVisible(true);
    }//GEN-LAST:event_bReturActionPerformed

    private void mKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKaryawanActionPerformed
        DataKaryawan show = new DataKaryawan();
        show.setVisible(true);
    }//GEN-LAST:event_mKaryawanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }
            
    public void hakAksesOperator(){
        
        mMaster.setVisible(false);
        bRegister.setVisible(false);
        mKonsinyasi.setVisible(false);
        jSeparator1.setVisible(false);
        jSeparator7.setVisible(false);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bExit;
    private javax.swing.JMenu bLogout;
    private javax.swing.JMenuItem bPenjualan;
    private javax.swing.JMenuItem bRegister;
    private javax.swing.JMenuItem bRetur;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JMenuItem mBarang;
    private javax.swing.JMenuItem mKaryawan;
    private javax.swing.JMenuItem mKonsinyasi;
    private javax.swing.JMenu mMaster;
    private javax.swing.JMenuItem mPenjualan;
    private javax.swing.JMenuItem mRetur;
    private javax.swing.JMenuItem mSupplier;
    private javax.swing.JMenu mTransaksi;
    // End of variables declaration//GEN-END:variables
}
