/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Master;

import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Rothem
 */
public class DataRetur extends javax.swing.JFrame {
    
    DefaultTableModel tabModel;

    /**
     * Creates new form DataRetur
     */
    public DataRetur() {
        initComponents();
        setLocationRelativeTo(this);
        setJTableRetur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tRetur = new javax.swing.JTable();
        bCancel = new javax.swing.JButton();
        bPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATA RETUR");

        tRetur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tRetur);

        bCancel.setText("BATAL");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        bPrint.setText("CETAK");
        bPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancel)
                    .addComponent(bPrint))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintActionPerformed
        printDataRetur();
    }//GEN-LAST:event_bPrintActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        dispose();
    }//GEN-LAST:event_bCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataRetur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataRetur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataRetur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataRetur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataRetur().setVisible(true);
            }
        });
    }
    
    public void getDataRetur(){
        
        try{            
            
            Connection conn = Koneksi.koneksiDatabase();
            String sql = "Select * From DetailRetur";
            PreparedStatement s = conn.prepareStatement(sql);
            ResultSet r = s.executeQuery();
            
            String NoRetur,NoFaktur,Product,Type,JmlBeli,JmlRetur,Note;
            while(r.next()){
            NoRetur = r.getString("NoRetur");
            NoFaktur = r.getString("NoFaktur");
            Product = r.getString("Product");
            Type = r.getString("Type");
            JmlBeli = r.getString("JmlBeli");
            JmlRetur = r.getString("JmlRetur");
            Note = r.getString("Note");
            
            Object Data[] = {NoRetur,NoFaktur,Product,Type,JmlBeli,JmlRetur,Note};
            tabModel.addRow(Data);
            }
            
            s.close();
            conn.close();
            
        }catch(SQLException sqle){
            JOptionPane.showMessageDialog(null,"" +sqle.getMessage());        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"" +e.getMessage());
        }
        
    }
    
    public void setJTableRetur(){
        
        String [] JudulKolom = {"No Retur","No Faktur","Product","Type","Total Beli","Total Retur","Note"};
        tabModel = new DefaultTableModel(null,JudulKolom){
            boolean[] canEdit = new boolean[] {false,false,false,false,false,false,false};
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex){
                return canEdit[columnIndex];
            }
        };
        
        tRetur.setModel(tabModel);
        tRetur.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tRetur.getColumnModel().getColumn(0).setPreferredWidth(100);
        tRetur.getColumnModel().getColumn(1).setPreferredWidth(100);
        tRetur.getColumnModel().getColumn(2).setPreferredWidth(100);
        tRetur.getColumnModel().getColumn(3).setPreferredWidth(100);
        tRetur.getColumnModel().getColumn(4).setPreferredWidth(100);
        tRetur.getColumnModel().getColumn(5).setPreferredWidth(100);
        tRetur.getColumnModel().getColumn(6).setPreferredWidth(100);
        
        getDataRetur();
        
    }
    
    public void printDataRetur(){
        
        String reportSource,reportDest;        

        try{
            
            Connection conn = Koneksi.koneksiDatabase();

            reportSource = System.getProperty("user.dir")+"html";
            reportDest = System.getProperty("user.dir")+"jrxml";

            JasperReport jasperReport=JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint=JasperFillManager.fillReport(jasperReport,null,conn);
            JasperExportManager.exportReportToHtmlFile(jasperPrint,reportDest);
            JasperViewer.viewReport(jasperPrint,false);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,""+e.getMessage());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tRetur;
    // End of variables declaration//GEN-END:variables
}
